version: '2.4'

networks:
  kafka_network:

services:

  zookeeper:
    image: zookeeper:3.4.14
    container_name: zookeeper
    hostname: zookeeper.myserver.com
    ports:
      - 2181:2181
    environment:
      SERVER_JVMFLAGS: -Xmx256m
      ZOO_LOG4J_PROP: "INFO,ROLLINGFILE,CONSOLE"
    healthcheck:
      test: nc -z localhost 2181 || exit 1
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - kafka_network

  kafka:
    image: wurstmeister/kafka:2.13-2.6.0
    container_name: kafka
    hostname: kafka.myserver.com
    ports:
      - 9092:9092
      - 9093:9093
    expose:
      - 9082
    environment:
      KAFKA_HEAP_OPTS: "-Xms128m -Xmx256m"
      KAFKA_BROKER_ID: 1
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9082,OUTSIDE://kafka.myserver.com:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9082,OUTSIDE://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_CREATE_TOPICS: "mytopic1:4:1,mytopic2:4:1"
      KAFKA_HEAP_OPTS: "-Xmx256m -Xms256m"
      JMX_PORT: 9093
      KAFKA_JMX_OPTS: -Dlog4j.logger.org.apache.kafka.common.network.Selector=ERROR
                      -Dcom.sun.management.jmxremote=true 
                      -Dcom.sun.management.jmxremote.authenticate=false 
                      -Dcom.sun.management.jmxremote.ssl=false 
                      -Djava.rmi.server.hostname=kafka.myserver.com
                      -Dcom.sun.management.jmxremote.rmi.port=9393 
                      -Djava.net.preferIPv4Stack=true
    depends_on:
      zookeeper:
        condition: service_healthy
    healthcheck:
      test: nc -z localhost 9092 || exit 1
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - kafka_network

  cmak:
    image: hlebalbau/kafka-manager:stable
    restart: always
    command:
      - "-Dcmak.zkhosts=zookeeper:2181"
      - "-DbasicAuthentication.enabled=true"
      - "-DbasicAuthentication.username=admin"
      - "-DbasicAuthentication.password=password"
    ports:
      - 9000:9000
    depends_on:
      zookeeper:
        condition: service_healthy
    networks:
      - kafka_network